--- Makefile	2024-01-07 10:45:49.007526037 -0700
+++ Makefile.diff	2024-01-07 10:47:22.980399601 -0700
@@ -41,7 +41,7 @@
 	mkdir -p $(DESTDIR)$(MANPREFIX)/man1
 	sed "s/VERSION/$(VERSION)/g" < st.1 > $(DESTDIR)$(MANPREFIX)/man1/st.1
 	chmod 644 $(DESTDIR)$(MANPREFIX)/man1/st.1
-	tic -sx st.info
+	sudo tic -sx st.info
 	@echo Please see the README file regarding the terminfo entry of st.
 
 uninstall:
