#!/usr/bin/bash

# Compile and execute a single-file C++ program from HackerRank.

# Create temporary files for storing the compiled C++ program and its output.
_bin="$(mktemp)"
_out="$(mktemp)"

# Compile with GCC using C++20
g++ -std=c++20 "$@" -o "$_bin" || exit 1

# Execute the compiled program.
OUTPUT_PATH="$_out" "$_bin"

# View the program output.
cat "$_out" || exit 1

# Delete the temporary file.
rm "$_bin" "$_out" || exit 1
