#!/usr/bin/bash

# Execute a Python program from HackerRank.

# Create a temporary file for storing the output.
_out="$(mktemp)"

# Execute the program.
OUTPUT_PATH="$_out" python "$@"

# View the program output.
cat "$_out" || exit 1

# Delete the temporary file.
rm "$_out" || exit 1
