#!/usr/bin/bash

# Compile and execute a single-file C++ program.

# Create a temporary file for storing the compiled C++ program.
_bin="$(mktemp)"

# Compile with GCC using C++20
g++ -std=c++20 "$@" -o "$_bin" || exit 1

# Execute the compiled program.
"$_bin"

# Delete the temporary file.
rm "$_bin" || exit 1
